/* GameBox — Tic-Tac-Toe + 8-Ball Pool */
let board=Array(9).fill(""),currentPlayer="X",result="playing",difficulty="hard",humanScore=0,aiScore=0,thinking=false,winningCells=[],aiTimer=null;
const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function openGame(kind){if(kind==='pool'){document.getElementById('home').classList.remove('active');document.getElementById('pool').classList.add('active');poolResize();resetPool();return}document.getElementById('home').classList.remove('active');document.getElementById('game').classList.add('active');render()}
function showHome(){['game','pool'].forEach(id=>document.getElementById(id).classList.remove('active'));document.getElementById('home').classList.add('active');stopPoolLoop()}
function render(animateIndex=null){const e=document.getElementById('board');if(!e)return;e.innerHTML='';board.forEach((v,i)=>{const b=document.createElement('button');b.className='cell'+(v==='X'?' x':'')+(v==='O'?' o':'')+(winningCells.includes(i)?' win':'');b.textContent=v;b.disabled=thinking||result!=='playing'||v!==''||currentPlayer!=='X';b.onclick=()=>playerMove(i);if(i===animateIndex&&v)b.classList.add('just-played');e.appendChild(b)});document.getElementById('humanScore').textContent=humanScore;document.getElementById('aiScore').textContent=aiScore;const s=document.getElementById('status');s.classList.remove('win-status','ai-status');if(result==='playing'){s.textContent=thinking?'AI is thinking…':'Your turn';if(thinking)s.classList.add('ai-status')}else if(result==='human'){s.textContent='You win 🎉';s.classList.add('win-status')}else if(result==='ai'){s.textContent='AI wins';s.classList.add('ai-status')}else s.textContent='Draw';document.querySelectorAll('.segmented button').forEach(b=>b.classList.toggle('selected',b.dataset.level===difficulty))}
function playerMove(i){if(thinking||result!=='playing'||board[i])return;board[i]='X';currentPlayer='O';if(finishIfNeeded('X')){render(i);return}thinking=true;render(i);aiTimer=setTimeout(()=>{const m=getAIMove();if(m!==null)board[m]='O';currentPlayer='X';thinking=false;finishIfNeeded('O');render(m);aiTimer=null},350)}
function finishIfNeeded(p){const pat=wins.find(r=>r.every(i=>board[i]===p));if(pat){winningCells=pat;p==='X'?humanScore++:aiScore++;result=p==='X'?'human':'ai';return true}if(board.every(Boolean)){result='draw';return true}return false}
function getAIMove(){const a=board.map((v,i)=>v===''?i:null).filter(v=>v!==null);if(!a.length)return null;if(difficulty==='easy')return a[Math.floor(Math.random()*a.length)];if(difficulty==='medium')return mediumMove(a);return bestMove()}
function mediumMove(a){const w=immediateMove('O');if(w!==null)return w;const bl=immediateMove('X');if(bl!==null)return bl;if(board[4]==='')return 4;const c=[0,2,6,8].filter(i=>!board[i]);return c.length?c[Math.floor(Math.random()*c.length)]:a[Math.floor(Math.random()*a.length)]}
function immediateMove(p){for(const i of board.keys()){if(board[i])continue;const t=[...board];t[i]=p;if(wins.some(r=>r.every(j=>t[j]===p)))return i}return null}
function bestMove(){let bs=-Infinity,ch=[];for(const i of board.keys()){if(board[i])continue;const t=[...board];t[i]='O';const sc=minimax(t,0,false);if(sc>bs){bs=sc;ch=[i]}else if(sc===bs)ch.push(i)}return ch[Math.floor(Math.random()*ch.length)]}
function minimax(s,d,max){if(isWinner('O',s))return 10-d;if(isWinner('X',s))return d-10;if(s.every(Boolean))return 0;if(max){let b=-Infinity;for(const i of s.keys())if(!s[i]){const n=[...s];n[i]='O';b=Math.max(b,minimax(n,d+1,false))}return b}let b=Infinity;for(const i of s.keys())if(!s[i]){const n=[...s];n[i]='X';b=Math.min(b,minimax(n,d+1,true))}return b}
function isWinner(p,s){return wins.some(r=>r.every(i=>s[i]===p))}
function newGame(){if(aiTimer)clearTimeout(aiTimer);aiTimer=null;board=Array(9).fill('');currentPlayer='X';result='playing';thinking=false;winningCells=[];render()}
function setDifficulty(l){if(thinking)return;difficulty=l;newGame()}

/* ---------- 8-BALL ---------- */
const pool={canvas:null,ctx:null,W:0,H:0,dpr:1,balls:[],cue:null,aim:0,power:48,drag:false,dragStart:null,turn:'human',phase:'aim',group:{human:null,ai:null},foul:false,shotPocketed:[],message:'Your turn · Aim and shoot',aiTimer:null,raf:null,ballsMoving:false,winner:null};
const ballColors=['#f7f7f3','#e3c047','#3f70ad','#cf433d','#8552a8','#df873d','#37936b','#9d3437','#121417'];
function poolInit(){pool.canvas=document.getElementById('poolCanvas');pool.ctx=pool.canvas.getContext('2d');const power=document.getElementById('power');power.oninput=()=>{pool.power=+power.value;document.getElementById('powerValue').textContent=power.value+'%'};pool.canvas.addEventListener('pointerdown',poolPointerDown);pool.canvas.addEventListener('pointermove',poolPointerMove);window.addEventListener('resize',poolResize);poolResize()}
function poolResize(){if(!pool.canvas)return;const wrap=pool.canvas.parentElement;const w=Math.min(wrap.clientWidth,700);const h=w/1.82;pool.dpr=Math.min(window.devicePixelRatio||1,2);pool.W=w;pool.H=h;pool.canvas.width=Math.round(w*pool.dpr);pool.canvas.height=Math.round(h*pool.dpr);pool.canvas.style.aspectRatio='1.82';if(pool.ctx)pool.ctx.setTransform(pool.dpr,0,0,pool.dpr,0,0);drawPool()}
function tableGeom(){const r=Math.max(12,pool.W*.035), left=r*1.9, top=r*1.9, right=pool.W-left,bottom=pool.H-top;return {left,top,right,bottom,r,innerR:r*.72}}
function resetPool(){if(!pool.canvas)poolInit();if(pool.aiTimer)clearTimeout(pool.aiTimer);pool.aiTimer=null;pool.group={human:null,ai:null};pool.turn='human';pool.phase='aim';pool.foul=false;pool.winner=null;pool.message='Your turn · Aim and shoot';pool.shotPocketed=[];pool.balls=[];const g=tableGeom(),cx=(g.left+g.right)/2,cy=(g.top+g.bottom)/2;pool.cue={x:g.left+(g.right-g.left)*.26,y:cy,vx:0,vy:0,r:(g.bottom-g.top)*.028,active:true};let rackX=g.left+(g.right-g.left)*.68;let n=1;const rows=[1,2,3,4,5];for(let row=0;row<5;row++){for(let j=0;j<=row;j++){let y=cy+(j-row/2)*(pool.cue.r*2.08);pool.balls.push(makeBall(n++,rackX+row*pool.cue.r*1.82,y,pool.cue.r))}}shuffleRack();poolResize();updatePoolUI();startPoolLoop()}
function makeBall(num,x,y,r){return {num,x,y,vx:0,vy:0,r,active:true,color:num===8?'#111':(num<=7?ballColors[num]:(num===9?'#d9bb4d':'#3f70ad')),stripe:num>=9}}
function shuffleRack(){const arr=pool.balls;const eight=arr.find(b=>b.num===8);if(eight){const idx=arr.indexOf(eight);[arr[4],arr[idx]]=[arr[idx],arr[4]]}}
function poolPointerDown(e){if(pool.turn!=='human'||pool.phase!=='aim'||pool.winner)return;pool.drag=true;pool.dragStart={x:e.clientX,y:e.clientY};pool.canvas.setPointerCapture?.(e.pointerId);poolPointerMove(e)}
function poolPointerMove(e){if(!pool.drag&&e.type==='pointermove')return;const rect=pool.canvas.getBoundingClientRect();const x=(e.clientX-rect.left)*pool.W/rect.width,y=(e.clientY-rect.top)*pool.H/rect.height;pool.aim=Math.atan2(y-pool.cue.y,x-pool.cue.x);drawPool()}
function playerShoot(){if(pool.turn!=='human'||pool.phase!=='aim'||pool.winner||!pool.cue.active)return;pool.drag=false;shootAt(pool.aim,pool.power/100);}
function shootAt(angle,pow){pool.phase='moving';pool.shotPocketed=[];pool.foul=false;const speed=pool.W*.0068*(.45+pow*1.05);pool.cue.vx=Math.cos(angle)*speed;pool.cue.vy=Math.sin(angle)*speed;pool.message=pool.turn==='human'?'Shot in motion…':'AI is shooting…';updatePoolUI()}
function allObjects(){return [pool.cue,...pool.balls.filter(b=>b.active)]}
function startPoolLoop(){if(pool.raf)cancelAnimationFrame(pool.raf);const step=()=>{physicsStep();drawPool();pool.raf=requestAnimationFrame(step)};pool.raf=requestAnimationFrame(step)}
function stopPoolLoop(){if(pool.raf)cancelAnimationFrame(pool.raf);pool.raf=null}
function physicsStep(){if(pool.phase!=='moving')return;const objs=allObjects();let moving=false;for(const b of objs){if(!b.active)continue;b.x+=b.vx;b.y+=b.vy;b.vx*=.986;b.vy*=.986;if(Math.hypot(b.vx,b.vy)<.035){b.vx=0;b.vy=0}else moving=true}handleCushions();handleCollisions();handlePockets();if(!moving){pool.phase='resolve';setTimeout(resolveShot,120)}}
function handleCushions(){const g=tableGeom();for(const b of allObjects()){if(!b.active)continue;if(b.x-b.r<g.left){b.x=g.left+b.r;b.vx=Math.abs(b.vx)*.88}if(b.x+b.r>g.right){b.x=g.right-b.r;b.vx=-Math.abs(b.vx)*.88}if(b.y-b.r<g.top){b.y=g.top+b.r;b.vy=Math.abs(b.vy)*.88}if(b.y+b.r>g.bottom){b.y=g.bottom-b.r;b.vy=-Math.abs(b.vy)*.88}}}
function handleCollisions(){const o=allObjects();for(let i=0;i<o.length;i++)for(let j=i+1;j<o.length;j++){const a=o[i],b=o[j];if(!a.active||!b.active)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r;if(d>0&&d<min){const nx=dx/d,ny=dy/d,over=min-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;const rvx=b.vx-a.vx,rvy=b.vy-a.vy,rel=rvx*nx+rvy*ny;if(rel<0){const impulse=-rel*.98;b.vx-=impulse*nx;b.vy-=impulse*ny;b.vx*=.995;b.vy*=.995;b.vx+=0;b.vy+=0;b.vx; b.vy; b.vx-=0;b.vy-=0;b.vx-=0;b.vy-=0;b.vx-=nx*0;b.vy-=ny*0;b.vx+=0;b.vy+=0;b.vx; b.vy; a.vx-=impulse*nx;a.vy-=impulse*ny;b.vx+=impulse*nx;b.vy+=impulse*ny}}}}
function pocketCenters(){const g=tableGeom(),p=g.r*1.15;return[{x:g.left,y:g.top},{x:(g.left+g.right)/2,y:g.top},{x:g.right,y:g.top},{x:g.left,y:g.bottom},{x:(g.left+g.right)/2,y:g.bottom},{x:g.right,y:g.bottom}].map(q=>({...q,r:p}))}
function handlePockets(){for(const b of allObjects()){if(!b.active)continue;for(const p of pocketCenters()){if(Math.hypot(b.x-p.x,b.y-p.y)<p.r){b.active=false;b.vx=b.vy=0;if(b===pool.cue){pool.foul=true;pool.shotPocketed.push('scratch')}else pool.shotPocketed.push(b.num);break}}}}
function resolveShot(){if(pool.winner)return;const pocketed=pool.shotPocketed.filter(x=>typeof x==='number');const scratch=pool.foul;if(pool.balls.find(b=>b.num===8&&!b.active)){if(pool.group[pool.turn]&&allGroupCleared(pool.turn)){endPool(pool.turn,'win')}else endPool(pool.turn==='human'?'ai':'human','8-ball early');return}if(scratch){pool.message=pool.turn==='human'?'Scratch — ball in hand for AI':'AI scratched — ball in hand';switchTurn(true);return}if(!pocketed.length){switchTurn(false);return}if(!pool.group.human&&!pool.group.ai){const first=pocketed.find(n=>n!==8);if(first){const humanGroup=first<=7?'solids':'stripes';pool.group[pool.turn]=humanGroup;pool.group[pool.turn==='human'?'ai':'human']=humanGroup==='solids'?'stripes':'solids'}}if(pool.group[pool.turn]&&pocketed.some(n=>groupOf(n)===pool.group[pool.turn])){pool.message=pool.turn==='human'?'Nice shot · Keep shooting':'AI pockets · AI shoots again';pool.phase='aim';updatePoolUI();if(pool.turn==='ai')aiTakeShot();return}switchTurn(false)}
function allGroupCleared(player){const g=pool.group[player];return g&&pool.balls.filter(b=>b.active&&groupOf(b.num)===g).length===0}
function groupOf(n){return n===8?'eight':n<=7?'solids':'stripes'}
function switchTurn(foul){pool.turn=pool.turn==='human'?'ai':'human';pool.phase='aim';pool.message=pool.turn==='human'?(foul?'Ball in hand · Your turn':'Your turn · Aim and shoot'):(foul?'Ball in hand · AI turn':'AI turn · Thinking…');updatePoolUI();if(pool.turn==='ai')aiTakeShot()}
function aiTakeShot(){if(pool.winner)return;pool.phase='aiThinking';updatePoolUI();pool.aiTimer=setTimeout(()=>{if(pool.winner)return;const target=chooseAITarget();if(!target){switchTurn(false);return}const a=Math.atan2(target.y-pool.cue.y,target.x-pool.cue.x);const pow=Math.max(.38,Math.min(.8,Math.hypot(target.x-pool.cue.x,target.y-pool.cue.y)/pool.W*.75));pool.phase='moving';pool.message='AI is shooting…';pool.shotPocketed=[];pool.foul=false;pool.cue.vx=Math.cos(a)*pool.W*.0068*(.45+pow*1.05);pool.cue.vy=Math.sin(a)*pool.W*.0068*(.45+pow*1.05);updatePoolUI();pool.aiTimer=null},900)}
function chooseAITarget(){let candidates=pool.balls.filter(b=>b.active&&b.num!==8);if(pool.group.ai)candidates=candidates.filter(b=>groupOf(b.num)===pool.group.ai);if(!candidates.length)candidates=pool.balls.filter(b=>b.active&&b.num===8);if(!candidates.length)return null;return candidates.sort((a,b)=>Math.hypot(a.x-pool.cue.x,a.y-pool.cue.y)-Math.hypot(b.x-pool.cue.x,b.y-pool.cue.y))[0]}
function endPool(who,why){pool.winner=who;pool.phase='over';pool.message=who==='human'?'You win 🎱':'AI wins';updatePoolUI()}
function updatePoolUI(){const s=document.getElementById('poolStatus');s.textContent=pool.message;s.classList.toggle('pool-win',!!pool.winner);document.getElementById('shootBtn').disabled=!(pool.turn==='human'&&pool.phase==='aim'&&!pool.winner);document.getElementById('poolYouGroup').textContent=pool.group.human||'Open';document.getElementById('poolAIGroup').textContent=pool.group.ai||'Open';const hp=pool.balls.filter(b=>!b.active&&b.num!==8&&groupOf(b.num)===pool.group.human).length;const ap=pool.balls.filter(b=>!b.active&&b.num!==8&&groupOf(b.num)===pool.group.ai).length;document.getElementById('poolScore').textContent=hp+' — '+ap}
function drawPool(){const c=pool.ctx;if(!c||!pool.W)return;const g=tableGeom();c.clearRect(0,0,pool.W,pool.H);const bg=c.createLinearGradient(0,0,0,pool.H);bg.addColorStop(0,'#0d1018');bg.addColorStop(1,'#07090e');c.fillStyle=bg;c.fillRect(0,0,pool.W,pool.H);c.save();roundRect(c,g.left-g.r,g.top-g.r,(g.right-g.left)+g.r*2,(g.bottom-g.top)+g.r*2,g.r*.65);c.fillStyle='#4a3425';c.fill();c.strokeStyle='rgba(255,255,255,.1)';c.lineWidth=1;c.stroke();const felt=c.createRadialGradient((g.left+g.right)/2,(g.top+g.bottom)/2,10,(g.left+g.right)/2,(g.top+g.bottom)/2,g.right-g.left);felt.addColorStop(0,'#18543c');felt.addColorStop(.75,'#0d422f');felt.addColorStop(1,'#082d21');c.fillStyle=felt;c.fillRect(g.left,g.top,g.right-g.left,g.bottom-g.top);c.restore();for(const p of pocketCenters()){const pg=c.createRadialGradient(p.x-2,p.y-2,2,p.x,p.y,p.r);pg.addColorStop(0,'#050607');pg.addColorStop(.75,'#020304');pg.addColorStop(1,'#000');c.fillStyle=pg;c.beginPath();c.arc(p.x,p.y,p.r,0,Math.PI*2);c.fill()}for(const b of pool.balls){if(b.active)drawBall(c,b)}if(pool.cue?.active)drawBall(c,{...pool.cue,num:0,color:'#f4f5f0',stripe:false});if(pool.turn==='human'&&pool.phase==='aim'&&pool.cue?.active&&!pool.winner){drawAim(c)}if(pool.phase==='over'){c.fillStyle='rgba(4,7,10,.5)';c.fillRect(g.left,g.top,g.right-g.left,g.bottom-g.top);c.fillStyle='#f0c66a';c.font='900 '+Math.max(22,pool.W*.045)+'px -apple-system,sans-serif';c.textAlign='center';c.fillText(pool.winner==='human'?'YOU WIN':'AI WINS',(g.left+g.right)/2,(g.top+g.bottom)/2+8)} }
function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}
function drawBall(c,b){c.save();c.shadowColor='rgba(0,0,0,.45)';c.shadowBlur=b.r*.65;c.shadowOffsetY=b.r*.35;const grad=c.createRadialGradient(b.x-b.r*.35,b.y-b.r*.42,b.r*.08,b.x,b.y,b.r);grad.addColorStop(0,'#fff');grad.addColorStop(.18,b.color);grad.addColorStop(1,shade(b.color,.55));c.fillStyle=grad;c.beginPath();c.arc(b.x,b.y,b.r,0,Math.PI*2);c.fill();c.shadowColor='transparent';if(b.stripe){c.fillStyle='rgba(248,248,242,.94)';c.beginPath();c.rect(b.x-b.r,b.y-b.r*.42,b.r*2,b.r*.84);c.fill();c.globalCompositeOperation='source-atop';c.fillStyle=grad;c.fillRect(b.x-b.r,b.y-b.r*.42,b.r*2,b.r*.84);c.globalCompositeOperation='source-over'}if(b.num>0){c.fillStyle='#f8f8f5';c.beginPath();c.arc(b.x,b.y,b.r*.39,0,Math.PI*2);c.fill();c.fillStyle='#17191d';c.font='900 '+Math.max(6,b.r*.48)+'px Arial';c.textAlign='center';c.textBaseline='middle';c.fillText(b.num,b.x,b.y+.2)}c.restore()}
function drawAim(c){const b=pool.cue,g=tableGeom(),len=pool.W*.32;const x2=b.x+Math.cos(pool.aim)*len,y2=b.y+Math.sin(pool.aim)*len;c.save();c.setLineDash([6,7]);c.strokeStyle='rgba(255,255,255,.75)';c.lineWidth=1.2;c.beginPath();c.moveTo(b.x,b.y);c.lineTo(x2,y2);c.stroke();c.setLineDash([]);const pull=pool.power/100*pool.W*.12;const sx=b.x-Math.cos(pool.aim)*(b.r*1.8+pull),sy=b.y-Math.sin(pool.aim)*(b.r*1.8+pull);const cueGrad=c.createLinearGradient(sx,sy,b.x,b.y);cueGrad.addColorStop(0,'#7a5437');cueGrad.addColorStop(.35,'#e6d0a4');cueGrad.addColorStop(.8,'#f3f0df');cueGrad.addColorStop(1,'#fff');c.strokeStyle=cueGrad;c.lineWidth=Math.max(3,b.r*.48);c.beginPath();c.moveTo(sx,sy);c.lineTo(b.x-Math.cos(pool.aim)*b.r, b.y-Math.sin(pool.aim)*b.r);c.stroke();c.restore()}
function shade(hex,f){let n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)*f)),g=Math.max(0,Math.min(255,((n>>8)&255)*f)),b=Math.max(0,Math.min(255,(n&255)*f));return `rgb(${r|0},${g|0},${b|0})`}
function showPoolRules(){document.getElementById('rulesModal').hidden=false}function closePoolRules(){document.getElementById('rulesModal').hidden=true}
document.addEventListener('DOMContentLoaded',()=>{poolInit();render()});
